apiVersion: v1
kind: Pod
metadata:
  name: my-csi-app
  namespace: adcs-issuer
  labels:
    app: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/tls"
        name: tls
      command: [ "sleep", "1000000" ]
  volumes:
    - name: tls
      csi:
        driver: csi.cert-manager.io
        readOnly: true
        volumeAttributes:
          csi.cert-manager.io/issuer-name: adcs-cluster-issuer #use specific name of issuer
          csi.cert-manager.io/issuer-kind: ClusterAdcsIssuer # type of issuer
          csi.cert-manager.io/issuer-group: adcs.certmanager.csf.nokia.com # issuer group 
          csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local
          csi.cert-manager.io/uri-sans: "spiffe://cluster.local/ns/${POD_NAMESPACE}/pod/${POD_NAME}/${POD_UID}"
          csi.cert-manager.io/common-name: "${SERVICE_ACCOUNT_NAME}.${POD_NAMESPACE}"