apiVersion: cert-manager.io/v1
kind: Certificate
metadata:

  name: adcs-sim-cert
  namespace: cert-manager
spec:
  commonName: example.com
  dnsNames:
  - adcs1.example.com
  - adcs2.example.com

  issuerRef:
    group: adcs.certmanager.csf.nokia.com
    kind: ClusterAdcsIssuer
    name: adcs-cluster-issuer-adcs-sim

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Your organization

  secretName: adcs-sim-secret
